(define (problem merry)
(:domain bagend)
(:objects
    niebieski czerwony zielony pomaranczowy rozowy

    n1 n2 n3 n4 n5
    czer1 czer2
    z1 z2 z3 z4
    zolt1 zolt2
    r1
    
    A B C D E F G H I  

    k1 k2 k3 k4 k5 k6 k7 k8 kp
    p1 p2 p3 p4 p5 p6 p7 p8 p9
)
(:init
    (przejscie F I niebieski)
    (przejscie I F niebieski)
    (przejscie I H niebieski)
    (przejscie H I niebieski)
    (przejscie H E czerwony)
    (przejscie E H czerwony)
    (przejscie E F niebieski)
    (przejscie F E niebieski)
    (przejscie E C zielony)
    (przejscie C E zielony)
    (przejscie C A czerwony)
    (przejscie A C czerwony)
    (przejscie A B pomaranczowy)
    (przejscie B D pomaranczowy)
    (przejscie D F zielony)
    (przejscie F D zielony)
    (przejscie F G rozowy)
    (kulka n1 F)
    (kulka n2 F)
    (kulka n3 I)
    (kulka n4 E)
    (kulka n5 C)
    (kulka zolt1 I)
    (kulka zolt2 C)
    (kulka czer1 H)
    (kulka czer2 D)
    (kulka z1 H)
    (kulka z2 E)
    (kulka z3 D)
    (kulka z4 A)
    (kulka r1 B)
    (kolor n1 niebieski)
    (kolor n2 niebieski)
    (kolor n3 niebieski)
    (kolor n4 niebieski)
    (kolor n5 niebieski)
    (kolor czer1 czerwony)
    (kolor czer2 czerwony)
    (kolor zolt1 pomaranczowy)
    (kolor zolt2 pomaranczowy)
    (kolor r1 rozowy)
    (kolor z1 zielony)
    (kolor z2 zielony)
    (kolor z3 zielony)
    (kolor z4 zielony)
    (merry F)
    (pokoj A)
    (pokoj B)
    (pokoj C)
    (pokoj D)
    (pokoj E)
    (pokoj F)
    (pokoj G)
    (pokoj H)
    (pokoj I)
    (not(posiada n1))
    (not(posiada n2))
    (not(posiada n3))
    (not(posiada n4))
    (not(posiada n5))
    (not(posiada czer1))
    (not(posiada czer2))
    (not(posiada zolt1))
    (not(posiada zolt2))
    (not(posiada z1))
    (not(posiada z2))
    (not(posiada z3))
    (not(posiada z4))
    (not(posiada r1))
    (puste kp)
    (klocek k5 p1)
    (klocek k4 p2)
    (klocek k1 p3)      ;  1 2 3
    (klocek k8 p4)      ;  4 5 6
    (klocek kp p5)      ;  7 8 9
    (klocek k3 p6)
    (klocek k7 p7)
    (klocek k2 p8)
    (klocek k6 p9)

    (sasiad p1 p2)
    (sasiad p2 p3)
    (sasiad p1 p4)
    (sasiad p2 p5)
    (sasiad p3 p6)
    (sasiad p4 p7)
    (sasiad p5 p8)
    (sasiad p6 p9)
    (sasiad p4 p5)
    (sasiad p5 p6)
    (sasiad p7 p8)
    (sasiad p8 p9)
    (sasiad p2 p1)
    (sasiad p3 p2)
    (sasiad p4 p1)
    (sasiad p5 p2)
    (sasiad p6 p3)
    (sasiad p7 p4)
    (sasiad p8 p5)
    (sasiad p9 p6)
    (sasiad p5 p4)
    (sasiad p6 p5)
    (sasiad p8 p7)
    (sasiad p9 p8)



)
(:goal (and
    (klocek k1 p1)
    (klocek k2 p2)
    (klocek k3 p3)      ;  1 2 3
    (klocek k4 p4)      ;  4 5 6
    (klocek k5 p5)      ;  7 8 9
    (klocek k6 p6)
    (klocek k7 p7)
    (klocek k8 p8)
    (klocek kp p9)
    (merry G)
    
))
)
