CREATE TABLE NAZWY_KATEGORII (
    NAZWA VARCHAR2(50) PRIMARY KEY
);

CREATE TABLE DZIALY (
    NAZWA_DZIALU VARCHAR2(50) PRIMARY KEY,
    OPIS VARCHAR2(1000) NOT NULL
);

CREATE TABLE AUTORZY (
    IMIE VARCHAR2(50),
    NAZWISKO VARCHAR2(50),
    DATA_URODZENIA DATE,
    NARODOWOSC VARCHAR2(50) NOT NULL,
    BIOGRAFIA VARCHAR2(1000) NOT NULL,
    PRIMARY KEY(IMIE, NAZWISKO, DATA_URODZENIA)
);

CREATE TABLE SALE (
    NAZWA VARCHAR2(50) PRIMARY KEY,
    NUMER NUMBER NOT NULL,
    LOKALIZACJA VARCHAR2(50) NOT NULL
);

CREATE TABLE DZIELA_SZTUKI (
    TYTUL VARCHAR2(50),
    DATA_POWSTANIA DATE,
    OPIS VARCHAR2(1000) NOT NULL,
    IMIE_AUTORA VARCHAR2(50),
    NAZWISKO_AUTORA VARCHAR2(50),
    DATA_URODZENIA_AUTORA DATE,
    KATEGORIA_DZIELA VARCHAR2(50) NOT NULL,
    FOREIGN KEY(IMIE_AUTORA, NAZWISKO_AUTORA, DATA_URODZENIA_AUTORA) REFERENCES AUTORZY(IMIE, NAZWISKO, DATA_URODZENIA),
    FOREIGN KEY(KATEGORIA_DZIELA) REFERENCES NAZWY_KATEGORII(NAZWA),
    PRIMARY KEY(TYTUL, DATA_POWSTANIA)
);

CREATE TABLE PRACOWNICY (
    IMIE VARCHAR2(50),
    NAZWISKO VARCHAR2(50),
    KONTAKT NUMBER,
    DATA_ZATRUDNIENIA DATE NOT NULL,
    MIESIECZNA_PENSJA NUMBER(5, 2) NOT NULL,
    DZIAL VARCHAR2(50) NOT NULL,
    FOREIGN KEY(DZIAL) REFERENCES DZIALY(NAZWA_DZIALU),
    PRIMARY KEY(IMIE, NAZWISKO, KONTAKT)
);

CREATE TABLE WYSTAWY (
    NAZWA_WYSTAWY VARCHAR2(50),
    DATA_ROZPOCZECIA DATE,
    DATA_ZAKONCZENIA DATE,
    OPIS VARCHAR2(1000) NOT NULL,
    WYSTAWIONE_PRZEZ_DZIAL VARCHAR2(50),
    FOREIGN KEY(WYSTAWIONE_PRZEZ_DZIAL) REFERENCES DZIALY(NAZWA_DZIALU),
    PRIMARY KEY(NAZWA_WYSTAWY, DATA_ROZPOCZECIA)
);

CREATE TABLE WYSTAWY_DZIALOW (
    NAZWA_WYSTAWY VARCHAR2(50),
    DATA_ROZPOCZECIA DATE,
    DZIAL VARCHAR2(50),
    FOREIGN KEY(DZIAL) REFERENCES DZIALY(NAZWA_DZIALU),
    FOREIGN KEY(NAZWA_WYSTAWY, DATA_ROZPOCZECIA) REFERENCES WYSTAWY(NAZWA_WYSTAWY, DATA_ROZPOCZECIA),
    PRIMARY KEY(NAZWA_WYSTAWY, DATA_ROZPOCZECIA, DZIAL)
);

CREATE TABLE DZIELO_NA_WYSTAWIE (
    TYTUL_DZIELA VARCHAR2(50),
    DATA_POWSTANIA DATE,
    DATA_DODANIA DATE,
    DATA_USUNIECIA DATE,
    NAZWA_WYSTAWY VARCHAR2(50),
    DATA_ROZPOCZECIA DATE,
    FOREIGN KEY(TYTUL_DZIELA, DATA_POWSTANIA) REFERENCES DZIELA_SZTUKI(TYTUL, DATA_POWSTANIA),
    FOREIGN KEY(NAZWA_WYSTAWY, DATA_ROZPOCZECIA) REFERENCES WYSTAWY(NAZWA_WYSTAWY, DATA_ROZPOCZECIA),
    PRIMARY KEY(TYTUL_DZIELA, DATA_POWSTANIA, DATA_DODANIA, NAZWA_WYSTAWY, DATA_ROZPOCZECIA)
);

CREATE TABLE SALE_WYSTAW (
    NAZWA_WYSTAWY VARCHAR2(50),
    DATA_ROZPOCZECIA DATE,
    NAZWA_SALI VARCHAR2(50) NOT NULL,
    FOREIGN KEY(NAZWA_SALI) REFERENCES SALE(NAZWA),
    FOREIGN KEY(NAZWA_WYSTAWY, DATA_ROZPOCZECIA) REFERENCES WYSTAWY(NAZWA_WYSTAWY, DATA_ROZPOCZECIA),
    PRIMARY KEY(NAZWA_WYSTAWY, DATA_ROZPOCZECIA, NAZWA_SALI)
);

CREATE TABLE BILETY (
    NR_BILETU NUMBER PRIMARY KEY,
    PESEL_KUPUJACEGO NUMBER NOT NULL,
    CENA NUMBER(4, 2) NOT NULL,
    RODZAJ_BILETU VARCHAR2(50) CHECK(RODZAJ_BILETU IN ('ULGOWY', 'NORMALNY')) NOT NULL
);

CREATE TABLE BILETY_WYSTAW (
    NAZWA_WYSTAWY VARCHAR2(50),
    DATA_ROZPOCZECIA DATE,
    NR_BILETU NUMBER,
    FOREIGN KEY(NR_BILETU) REFERENCES BILETY(NR_BILETU),
    FOREIGN KEY(NAZWA_WYSTAWY, DATA_ROZPOCZECIA) REFERENCES WYSTAWY(NAZWA_WYSTAWY, DATA_ROZPOCZECIA),
    PRIMARY KEY(NAZWA_WYSTAWY, DATA_ROZPOCZECIA, NR_BILETU)
);

--Sprzedane bilety wedlug wystaw działów (Pokazuje które działy są bardziej pożądane)
CREATE OR REPLACE PROCEDURE OBLICZ_WARTOSC_BILETOW_DZIALU(
    P_NAZWA_DZIALU IN DZIALY.NAZWA_DZIALU%TYPE,
    P_WYNIK OUT NUMBER
) AS
BEGIN
    SELECT NVL(SUM(B.CENA), 0)
    INTO P_WYNIK
    FROM BILETY B
    JOIN BILETY_WYSTAW BW ON B.NR_BILETU = BW.NR_BILETU
    JOIN WYSTAWY W ON BW.NAZWA_WYSTAWY = W.NAZWA_WYSTAWY AND BW.DATA_ROZPOCZECIA = W.DATA_ROZPOCZECIA
    WHERE W.WYSTAWIONE_PRZEZ_DZIAL = P_NAZWA_DZIALU;
END;

--Średnia miesięczna pensja w dziale
CREATE OR REPLACE PROCEDURE OBLICZ_SREDNIA_PENSJA_DZIALU(
    P_NAZWA_DZIALU IN DZIALY.NAZWA_DZIALU%TYPE,
    P_SREDNIA OUT NUMBER
) AS
BEGIN
    SELECT NVL(AVG(MIESIECZNA_PENSJA), 0)
    INTO P_SREDNIA
    FROM PRACOWNICY
    WHERE DZIAL = P_NAZWA_DZIALU;
END;

--Obliczanie dochodu (Przychód z biletów - koszt pracowników)
CREATE OR REPLACE PROCEDURE PRZYCHOD_MINUS_KOSZTY(
    P_NAZWA_DZIALU IN DZIALY.NAZWA_DZIALU%TYPE,
    P_ROZNICA OUT NUMBER
) AS
    V_PRZYCHOD NUMBER := 0;
    V_KOSZTY NUMBER := 0;
BEGIN
    -- Obliczenie przychodu z biletów
    SELECT NVL(SUM(B.CENA), 0)
    INTO V_PRZYCHOD
    FROM BILETY B
    JOIN BILETY_WYSTAW BW ON B.NR_BILETU = BW.NR_BILETU
    JOIN WYSTAWY W ON BW.NAZWA_WYSTAWY = W.NAZWA_WYSTAWY AND BW.DATA_ROZPOCZECIA = W.DATA_ROZPOCZECIA
    WHERE W.WYSTAWIONE_PRZEZ_DZIAL = P_NAZWA_DZIALU;

    -- Obliczenie kosztów wynagrodzeń
    SELECT NVL(SUM(MIESIECZNA_PENSJA), 0)
    INTO V_KOSZTY
    FROM PRACOWNICY
    WHERE DZIAL = P_NAZWA_DZIALU;

    -- Obliczenie różnicy
    P_ROZNICA := V_PRZYCHOD - V_KOSZTY;
END;

--Przeniesienie dzieła na inną wystawę
CREATE OR REPLACE PROCEDURE PRZENIES_DZIELO(
    P_TYTUL IN DZIELA_SZTUKI.TYTUL%TYPE,
    P_DATA_POWSTANIA IN DZIELA_SZTUKI.DATA_POWSTANIA%TYPE,
    P_OBECNA_WYSTAWA IN WYSTAWY.NAZWA_WYSTAWY%TYPE,
    P_NOWA_WYSTAWA IN WYSTAWY.NAZWA_WYSTAWY%TYPE
) AS
BEGIN
    UPDATE DZIELO_NA_WYSTAWIE
    SET NAZWA_WYSTAWY = P_NOWA_WYSTAWA
    WHERE TYTUL_DZIELA = P_TYTUL
      AND DATA_POWSTANIA = P_DATA_POWSTANIA
      AND NAZWA_WYSTAWY = P_OBECNA_WYSTAWA;
END;

--Dodanie dziela do tabeli dzielo na wystawie
CREATE OR REPLACE TRIGGER trg_insert_dzielo_na_wystawie
AFTER INSERT ON DZIELA_SZTUKI
FOR EACH ROW
BEGIN
    INSERT INTO DZIELO_NA_WYSTAWIE (
        TYTUL_DZIELA, DATA_POWSTANIA, DATA_DODANIA, NAZWA_WYSTAWY, DATA_ROZPOCZECIA
    )
    VALUES (
        :NEW.TYTUL, :NEW.DATA_POWSTANIA, NULL, NULL, NULL
    );
END;

--Funkcja do obliczania dziel na wystawie
CREATE OR REPLACE FUNCTION LICZBA_DZIEL_NA_WYSTAWIE (
    P_NAZWA_WYSTAWY IN DZIELO_NA_WYSTAWIE.NAZWA_WYSTAWY%TYPE,
    P_DATA_ROZPOCZECIA IN DZIELO_NA_WYSTAWIE.DATA_ROZPOCZECIA%TYPE
) RETURN NUMBER IS
    V_LICZBA NUMBER;
BEGIN
    SELECT COUNT(*)
    INTO V_LICZBA
    FROM DZIELO_NA_WYSTAWIE
    WHERE NAZWA_WYSTAWY = P_NAZWA_WYSTAWY
      AND DATA_ROZPOCZECIA = P_DATA_ROZPOCZECIA;

    RETURN V_LICZBA;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RETURN 0;
END;

--Funkcja do obliczania przychodu z wystawy
CREATE OR REPLACE FUNCTION PRZYCHOD_Z_WYSTAWY (
    P_NAZWA_WYSTAWY IN WYSTAWY.NAZWA_WYSTAWY%TYPE,
    P_DATA_ROZPOCZECIA IN WYSTAWY.DATA_ROZPOCZECIA%TYPE
) RETURN NUMBER IS
    V_PRZYCHOD NUMBER;
BEGIN
    SELECT NVL(SUM(B.CENA), 0)
    INTO V_PRZYCHOD
    FROM BILETY B
    JOIN BILETY_WYSTAW BW ON B.NR_BILETU = BW.NR_BILETU
    WHERE BW.NAZWA_WYSTAWY = P_NAZWA_WYSTAWY
      AND BW.DATA_ROZPOCZECIA = P_DATA_ROZPOCZECIA;

    RETURN V_PRZYCHOD;
END;




