ZAD.1 
SELECT * FROM ZESPOLY ORDER BY ID_ZESP
ZAD.2
SELECT * FROM PRACOWNICY ORDER BY ID_PRAC
ZAD.3
SELECT NAZWISKO, PLACA_POD*12 AS "ROCZNA PLACA" 
FROM PRACOWNICY 
ORDER BY NAZWISKO
ZAD.4
SELECT NAZWISKO,ETAT, PLACA_POD + COALESCE(PLACA_DOD, 0) AS MIESIECZNE_ZAROBKI
FROM PRACOWNICY 
ORDER BY MIESIECZNE_ZAROBKI DESC
ZAD.5
SELECT * FROM ZESPOLY ORDER BY NAZWA
ZAD.6
SELECT UNIQUE ETAT FROM PRACOWNICY
ZAD.7
SELECT *
FROM PRACOWNICY 
WHERE ETAT = 'ASYSTENT'
ORDER BY NAZWISKO
ZAD.8
SELECT ID_PRAC, NAZWISKO, ETAT, PLACA_POD, ID_ZESP 
FROM PRACOWNICY 
WHERE ID_ZESP IN ('30','40')
ORDER BY PLACA_POD DESC
ZAD.9
SELECT NAZWISKO, ID_ZESP, PLACA_POD 
FROM PRACOWNICY 
WHERE PLACA_POD BETWEEN 300 AND 800
ORDER BY NAZWISKO
ZAD.10
SELECT NAZWISKO, ETAT, ID_ZESP 
FROM PRACOWNICY 
WHERE NAZWISKO LIKE '%SKI'
ORDER BY NAZWISKO
ZAD.11
SELECT ID_PRAC, ID_SZEFA, NAZWISKO, PLACA_POD 
FROM PRACOWNICY 
WHERE ID_SZEFA IS NOT NULL AND
PLACA_POD >1000
ZAD.12
SELECT NAZWISKO, ID_ZESP
FROM PRACOWNICY
WHERE ID_ZESP = 20 AND 
(NAZWISKO LIKE 'M%' OR NAZWISKO LIKE '%SKI')
ORDER BY NAZWISKO
ZAD.13
SELECT NAZWISKO, ETAT, PLACA_POD/160 AS STAWKA
FROM PRACOWNICY
WHERE ETAT NOT IN('ASYSTENT','STAZYSTA','ADIUNKTAM') AND 
(PLACA_POD NOT BETWEEN 400 AND 800)
ORDER BY  STAWKA 
ZAD.14
SELECT NAZWISKO, ETAT, PLACA_POD, PLACA_DOD 
FROM PRACOWNICY
WHERE PLACA_POD+COALESCE(PLACA_DOD, 0) > 1000
ORDER BY ETAT, NAZWISKO 
ZAD.15
SELECT NAZWISKO || ' PRACUJE OD ' || ZATRUDNIONY || ' I ZARABIA ' || PLACA_POD AS PROFESOROWIE
FROM PRACOWNICY
WHERE ETAT = 'PROFESOR'
ORDER BY PLACA_POD DESC
