ZAD.1

SELECT NAZWISKO, SUBSTR(ETAT,1,2) || TO_CHAR(ID_PRAC) AS KOD 
FROM PRACOWNICY
ZAD.2
SELECT NAZWISKO, TRANSLATE(NAZWISKO, 'KLM', 'XXX') AS WOJNA_LITEROM
FROM PRACOWNICY

ZAD.3
SELECT NAZWISKO
FROM PRACOWNICY
WHERE INSTR(NAZWISKO, 'L',1,1) BETWEEN 1 AND LENGTH(NAZWISKO)/2;

ZAD.4
SELECT NAZWISKO, ROUND(PLACA_POD*1.15,0)
FROM PRACOWNICY

ZAD.5
SELECT NAZWISKO, PLACA_POD, PLACA_POD*0.2 AS INWESTYCJA, PLACA_POD*0.2*POWER((1+0.1),10) AS KAPITAL, (PLACA_POD*0.2*POWER((1+0.1),10))-PLACA_POD*0.2 AS ZYSK
FROM PRACOWNICY

ZAD.6
SELECT nazwisko, ZATRUDNIONY,  FLOOR((DATE '2000-01-01' - zatrudniony)/365) AS staz_w_2000_r
FROM pracownicy 

ZAD.7
SELECT NAZWISKO, TO_CHAR(ZATRUDNIONY, 'MONTH, DD YYYY')  AS DATA_ZATRUDNIENIA
FROM PRACOWNICY
WHERE ID_ZESP=20

ZAD.8
SELECT  UNIQUE TO_CHAR(CURRENT_DATE,'DAY') AS DZIS
FROM PRACOWNICY

ZAD.9
SELECT NAZWA,ADRES,
CASE ADRES
    WHEN 'PIOTROWO 3A' THEN 'NOWE MIASTO'
    WHEN 'WLODKOWICA 16' THEN 'GRUNWALD'
    WHEN 'STRZELECKA 14' THEN 'STARE MIASTO'
    WHEN 'MIELZYNSKIEGO 30' THEN 'STARE MIASTO'
    ELSE 'INNE'
    END AS DZIELNICA
FROM ZESPOLY

ZAD.10
SELECT NAZWISKO,PLACA_POD,
CASE
    WHEN PLACA_POD<480 THEN 'PONIZEJ 480'
    WHEN PLACA_POD>480 THEN 'POWYZEJ 480'
    ELSE 'DOKLADNIE 480'
    END AS PROG
FROM PRACOWNICY
ORDER BY PLACA_POD DESC
