ZAD.1

SELECT MIN(PLACA_POD) AS MINIMUM, MAX(PLACA_POD) AS MAKSIMUM, MAX(PLACA_POD)-MIN(PLACA_POD) AS ROZNICA
FROM PRACOWNICY

ZAD.2
SELECT UNIQUE ETAT, AVG(PLACA_POD)
FROM PRACOWNICY
GROUP BY ETAT 

ZAD.3
SELECT COUNT(NAZWISKO) AS PROFESOROWIE
FROM PRACOWNICY
WHERE ETAT='PROFESOR'

ZAD.4
SELECT ID_ZESP, SUM(PLACA_DOD)+SUM(PLACA_POD) AS SUMARYCZNE_PLACE
FROM PRACOWNICY
GROUP BY ID_ZESP

ZAD.5
SELECT MAX(SUMARYCZNE_PLACE) AS MAKS_SUM_PLACA
FROM(SELECT SUM(PLACA_DOD)+SUM(PLACA_POD) AS SUMARYCZNE_PLACE
FROM PRACOWNICY GROUP BY ID_ZESP)

ZAD.6

SELECT ID_SZEFA, MIN(PLACA_POD)
FROM  PRACOWNICY
WHERE ID_SZEFA IS NOT NULL
GROUP BY ID_SZEFA

ZAD.7
SELECT ID_ZESP, COUNT(NAZWISKO) AS ILU_PRACUJE
FROM PRACOWNICY
GROUP BY ID_ZESP

ZAD.8
SELECT ID_ZESP, COUNT(NAZWISKO) AS ILU_PRACUJE
FROM PRACOWNICY
HAVING COUNT(NAZWISKO)>3
GROUP BY ID_ZESP

ZAD.9
SELECT COUNT(*) as ZDUBLOWANE_ID 
FROM pracownicy 
GROUP BY id_prac HAVING COUNT(*) > 1;

ZAD.10
SELECT ETAT, AVG(PLACA_POD), COUNT(NAZWISKO)
FROM(SELECT ETAT, PLACA_POD, NAZWISKO
FROM PRACOWNICY
WHERE ZATRUDNIONY < DATE '1990-01-01')
GROUP BY ETAT

ZAD.11
SELECT ID_ZESP, ETAT, CEIL(AVG(PLACA_POD)+AVG(NVL(PLACA_DOD,0))) AS SREDNIA, CEIL(MAX(PLACA_POD+NVL(PLACA_DOD,0))) AS MAKSYMALNA
FROM PRACOWNICY
WHERE ETAT IN('ASYSTENT','PROFESOR')
GROUP BY ID_ZESP, ETAT
ORDER BY ID_ZESP, ETAT

ZAD.12
SELECT ROK, COUNT(ILOSC) AS ILU_ZATRUDNIONYCH
FROM(SELECT EXTRACT(YEAR FROM ZATRUDNIONY) AS ROK, NAZWISKO AS ILOSC
FROM PRACOWNICY)
GROUP BY ROK

ZAD.13
SELECT LENGTH(NAZWISKO), COUNT(*)
FROM PRACOWNICY
GROUP BY LENGTH(NAZWISKO)

ZAD.14
SELECT COUNT(NAZWISKO) AS ILE_NAZWISK_Z_A
FROM PRACOWNICY
WHERE NAZWISKO LIKE '%A%'

ZAD.15
SELECT SUM(CASE WHEN NAZWISKO LIKE '%a%' OR NAZWISKO LIKE '%A%' THEN 1 ELSE 0 END) AS "ILE NAZWISK Z  A",
SUM(CASE WHEN NAZWISKO LIKE '%e%' OR NAZWISKO LIKE '%E%' THEN 1 ELSE 0 END) AS "ILE NAZWISK Z E"
FROM PRACOWNICY;

ZAD.16
SELECT ID_ZESP, SUM(PLACA_POD) AS SUMA_PLAC, LISTAGG(NAZWISKO || ': ' || PLACA_POD, ' ; ') AS PRACOWNICY
FROM PRACOWNICY
GROUP BY ID_ZESP
ORDER BY ID_ZESP
