zad.1

SELECT nazwisko, p.ID_ZESP, z.NAZWA
FROM pracownicy p left OUTER JOIN ZESPOLY z
ON z.id_zesp = p.id_zesp
order by nazwisko;

ZAD.2
SELECT z.nazwa, z.ID_ZESP, COALESCE(p.NAZWISKO, 'BRAK PRACOWNIKOW')
FROM pracownicy p right OUTER JOIN ZESPOLY z
ON z.id_zesp = p.id_zesp
order by z.NAZWA, p.NAZWISKO;

ZAD.3
SELECT COALESCE(z.NAZWA, 'BRAK ZESPOLU') AS ZESPOL, COALESCE(p.NAZWISKO, 'BRAK PRACOWNIKOW') AS PRACOWNIK
FROM pracownicy p FULL OUTER JOIN ZESPOLY z
ON z.id_zesp = p.id_zesp
order by z.NAZWA, p.NAZWISKO;

ZAD.4
SELECT z.NAZWA AS ZESPOL, COUNT(p.ID_PRAC) AS LICZBA, SUM(COALESCE(p.PLACA_POD, 0)) AS SUMA_PLAC
FROM pracownicy p RIGHT OUTER JOIN ZESPOLY z
ON z.id_zesp = p.id_zesp
GROUP BY z.NAZWA;

ZAD.5
SELECT z.NAZWA AS ZESPOL, COUNT(p.ID_PRAC) AS LICZBA
FROM pracownicy p RIGHT OUTER JOIN ZESPOLY z
ON z.id_zesp = p.id_zesp
HAVING COUNT(p.ID_PRAC) = 0
GROUP BY z.NAZWA;

ZAD.6
SELECT p.nazwisko AS pracownik,p.ID_PRAC, s.nazwisko AS szef, p.ID_SZEFA
FROM pracownicy p LEFT OUTER JOIN pracownicy s
ON p.id_szefa = s.id_prac
ORDER BY P.NAZWISKO;

ZAD.7
SELECT s.nazwisko AS szef, COUNT(p.ID_SZEFA)
FROM pracownicy p RIGHT OUTER JOIN pracownicy s
ON p.id_szefa = s.id_prac
GROUP BY s.NAZWISKO
ORDER BY s.NAZWISKO

ZAD.8
SELECT p.NAZWISKO AS PRACOWNIK, P.ETAT, p.PLACA_POD, Z.NAZWA, s.NAZWISKO AS SZEF
FROM pracownicy p LEFT OUTER JOIN pracownicy s
ON p.id_szefa = s.id_prac
LEFT OUTER JOIN ZESPOLY Z
ON p.ID_ZESP = Z.ID_ZESP
ORDER BY 1

ZAD.9
SELECT NAZWISKO, NAZWA
FROM PRACOWNICY CROSS JOIN ZESPOLY 
ORDER BY NAZWISKO

ZAD.10
SELECT COUNT(*)
FROM PRACOWNICY CROSS JOIN ZESPOLY CROSS JOIN ETATY

ZAD.11
SELECT etat FROM pracownicy
WHERE EXTRACT(YEAR FROM zatrudniony) = 1993
INTERSECT
SELECT etat FROM pracownicy
WHERE EXTRACT(YEAR FROM zatrudniony) = 1992 
ORDER BY etat;

ZAD.12
SELECT ID_ZESP FROM ZESPOLY
MINUS 
SELECT UNIQUE(ID_ZESP) FROM PRACOWNICY

ZAD.13
SELECT ID_ZESP, NAZWA
FROM ZESPOLY
MINUS
SELECT P.ID_ZESP, NAZWA
FROM ZESPOLY Z RIGHT JOIN PRACOWNICY P
ON Z.ID_ZESP=P.ID_ZESP


ZAD.14
SELECT NAZWISKO, PLACA_POD, 'PONIZEJ 480' AS PROG
FROM PRACOWNICY
WHERE PLACA_POD<480
UNION
SELECT NAZWISKO, PLACA_POD, 'DOKLADNIE 480' AS PROG
FROM PRACOWNICY
WHERE PLACA_POD=480
UNION
SELECT NAZWISKO, PLACA_POD, 'POWYZEJ 480' AS PROG
FROM PRACOWNICY
WHERE PLACA_POD>480
ORDER BY PLACA_POD
