ZAD.1

SELECT NAZWISKO, ETAT, ID_ZESP
FROM PRACOWNICY
WHERE ID_ZESP =
(SELECT ID_ZESP
FROM PRACOWNICY
WHERE NAZWISKO='BRZEZINSKI')
ORDER BY NAZWISKO

ZAD.2
SELECT NAZWISKO, ETAT, NAZWA
FROM PRACOWNICY P JOIN ZESPOLY Z
ON P.ID_ZESP = Z.ID_ZESP
WHERE P.ID_ZESP =
(SELECT ID_ZESP
FROM PRACOWNICY
WHERE NAZWISKO='BRZEZINSKI')
ORDER BY NAZWISKO

ZAD.3
SELECT NAZWISKO, ETAT, ZATRUDNIONY
FROM PRACOWNICY
WHERE (ZATRUDNIONY, ETAT) =
(SELECT MIN(ZATRUDNIONY), 'PROFESOR'
FROM PRACOWNICY
WHERE ETAT= 'PROFESOR')

ZAD.4
SELECT NAZWISKO, ZATRUDNIONY, ID_ZESP
FROM PRACOWNICY
WHERE (ZATRUDNIONY,ID_ZESP) IN
(SELECT MIN(ZATRUDNIONY), ID_ZESP
FROM PRACOWNICY
GROUP BY ID_ZESP)

ZAD.5
SELECT *
FROM ZESPOLY
WHERE ID_ZESP NOT IN
(SELECT UNIQUE ID_ZESP
FROM PRACOWNICY
WHERE ID_ZESP IS NOT NULL)

ZAD.6
SELECT NAZWISKO, ETAT
FROM PRACOWNICY 
WHERE ID_PRAC NOT IN
(SELECT ID_SZEFA
FROM PRACOWNICY
WHERE ETAT LIKE 'STAZYSTA'
)
AND ETAT='PROFESOR'

ZAD.7
SELECT ID_ZESP, SUM(PLACA_POD) AS SUMA_PLAC
FROM PRACOWNICY
HAVING SUM(PLACA_POD)=
(SELECT MAX(SUMA)
FROM(
SELECT ID_ZESP, SUM(PLACA_POD) AS SUMA
FROM PRACOWNICY
GROUP BY ID_ZESP))
GROUP BY ID_ZESP


ZAD.8
SELECT ZESPOLY.NAZWA, SUM(PLACA_POD) AS SUMA_PLAC
FROM PRACOWNICY JOIN ZESPOLY
ON PRACOWNICY.ID_ZESP = ZESPOLY.ID_ZESP
HAVING SUM(PLACA_POD)=
(SELECT MAX(SUMA)
FROM(
SELECT ID_ZESP, SUM(PLACA_POD) AS SUMA
FROM PRACOWNICY
GROUP BY ID_ZESP))
GROUP BY ZESPOLY.NAZWA

ZAD.9
SELECT ZESPOLY.NAZWA, COUNT(PRACOWNICY.ID_ZESP)
FROM PRACOWNICY JOIN ZESPOLY
ON PRACOWNICY.ID_ZESP = ZESPOLY.ID_ZESP
HAVING COUNT(PRACOWNICY.ID_ZESP) > 
(SELECT COUNT(ID_ZESP)
FROM PRACOWNICY
WHERE ID_ZESP =
(SELECT ID_ZESP
FROM ZESPOLY
WHERE NAZWA = 'ADMINISTRACJA')
GROUP BY ID_ZESP)
GROUP BY ZESPOLY.NAZWA

ZAD.10
SELECT ETAT
FROM PRACOWNICY
HAVING COUNT(ETAT) = 
(SELECT MAX(COUNT(ETAT))
FROM PRACOWNICY
GROUP BY ETAT)
GROUP BY ETAT

ZAD.11
SELECT ETAT, LISTAGG(NAZWISKO,',')
FROM PRACOWNICY
HAVING COUNT(ETAT) = 
(SELECT MAX(COUNT(ETAT))
FROM PRACOWNICY
GROUP BY ETAT)
GROUP BY ETAT

ZAD.12
