ZAD.1

CREATE TABLE PROJEKTY (
    ID_PROJEKTU INT GENERATED ALWAYS AS IDENTITY,
    OPIS_PROJEKTU VARCHAR(20),
    DATA_ROZPOCZECIA DATE DEFAULT CURRENT_DATE,
    DATA_ZAKONCZENIA DATE,
    FUNDUSZ NUMBER(7, 2)
);

ZAD.2
INSERT INTO PROJEKTY (OPIS_PROJEKTU, DATA_ROZPOCZECIA, DATA_ZAKONCZENIA, FUNDUSZ)
VALUES ('Indeksy bitmapowe', '1999-04-02', '2001-08-31', 25000.00);

INSERT INTO PROJEKTY (OPIS_PROJEKTU, DATA_ROZPOCZECIA, DATA_ZAKONCZENIA, FUNDUSZ)
VALUES ('Sieci kręgosłupowe', DEFAULT, '', 19000);

ZAD.3
SELECT ID_PROJEKTU, OPIS_PROJEKTU
FROM PROJEKTY

ZAD.4
INSERT INTO PROJEKTY (OPIS_PROJEKTU, DATA_ROZPOCZECIA, DATA_ZAKONCZENIA, FUNDUSZ)
VALUES ('Indeksy drzewiaste', '2013-12-24', '2014-01-01', 1200);


ZAD.5

UPDATE PROJEKTY 
SET ID_PROJEKTU=10
WHERE OPIS_PROJEKTU='Indeksy drzewiaste'

ZAD.6
create table PROJEKTY_KOPIA AS * FROM PROJEKTY
ZAD.7
INSERT INTO PROJEKTY_KOPIA (ID_PROJEKTU, OPIS_PROJEKTU, DATA_ROZPOCZECIA, DATA_ZAKONCZENIA, FUNDUSZ)
VALUES (10, 'Sieci lokalne', SYSDATE, ADD_MONTHS(SYSDATE, 12), 24500.00);
ZAD.8
DELETE FROM PROJEKTY
WHERE OPIS_PROJEKTU = 'Indeksy drzewiaste';
ZAD.9
SELECT table_name
FROM user_tables;
