ZAD.1

ALTER TABLE PROJEKTY ADD CONSTRAINT PK_PROJEKTY PRIMARY KEY (ID_PROJEKTU);

ALTER TABLE PROJEKTY ADD CONSTRAINT UK_PROJEKTY UNIQUE (OPIS_PROJEKTU);

ALTER TABLE PROJEKTY MODIFY OPIS_PROJEKTU NOT NULL;

ALTER TABLE PROJEKTY MODIFY OPIS_PROJEKTU NOT NULL;

ALTER TABLE PROJEKTY ADD CONSTRAINT CHK_DATY CHECK (DATA_ZAKONCZENIA > DATA_ROZPOCZECIA);

ALTER TABLE PROJEKTY ADD CONSTRAINT CHK_FUNDUSZ CHECK (FUNDUSZ > 0 OR FUNDUSZ IS NULL);

ZAD.2
INSERT INTO PROJEKTY (OPIS_PROJEKTU, DATA_ROZPOCZECIA, DATA_ZAKONCZENIA, FUNDUSZ)
VALUES ('Indeksy bitmapowe', '2015-04-15', '2016-09-30', 40000);

ZAD.3
CREATE TABLE PRZYDZIALY ( ID_PROJEKTU NUMBER(4) NOT NULL, NR_PRACOWNIKA NUMBER(6) NOT NULL, PRZYDZIAL_OD DATE DEFAULT SYSDATE, PRZYDZIAL_DO DATE, STAWKA NUMBER(7,2) CONSTRAINT CHK_PRZYDZIALY_STAWKA CHECK (STAWKA > 0), ROLA VARCHAR2(20) CONSTRAINT CHK_PRZYDZIALY_ROLA CHECK (ROLA IN ('KIERUJĄCY', 'ANALITYK', 'PROGRAMISTA')), CONSTRAINT FK_PRZYDZIALY_01 FOREIGN KEY (ID_PROJEKTU) REFERENCES PROJEKTY(ID_PROJEKTU), CONSTRAINT FK_PRZYDZIALY_02 FOREIGN KEY (NR_PRACOWNIKA) REFERENCES PRACOWNICY(ID_PRAC), CONSTRAINT CHK_PRZYDZIALY_DATY CHECK (PRZYDZIAL_DO > PRZYDZIAL_OD) );

ZAD.4
INSERT INTO PRZYDZIALY (ID_PROJEKTU, NR_PRACOWNIKA, PRZYDZIAL_OD, PRZYDZIAL_DO, STAWKA, ROLA)
VALUES ((SELECT ID_PROJEKTU FROM PROJEKTY WHERE OPIS_PROJEKTU = 'Indeksy bitmapowe'), 170, TO_DATE('10-APR-1999', 'DD-MON-YYYY'), TO_DATE('10-MAY-1999', 'DD-MON-YYYY'), 1000, 'KIERUJĄCY');

INSERT INTO PRZYDZIALY (ID_PROJEKTU, NR_PRACOWNIKA, PRZYDZIAL_OD, PRZYDZIAL_DO, STAWKA, ROLA)
VALUES ((SELECT ID_PROJEKTU FROM PROJEKTY WHERE OPIS_PROJEKTU = 'Indeksy bitmapowe'), 140, TO_DATE('01-DEC-2000', 'DD-MON-YYYY'), NULL, 1500, 'ANALITYK');

INSERT INTO PRZYDZIALY (ID_PROJEKTU, NR_PRACOWNIKA, PRZYDZIAL_OD, PRZYDZIAL_DO, STAWKA, ROLA)
VALUES ((SELECT ID_PROJEKTU FROM PROJEKTY WHERE OPIS_PROJEKTU = 'Sieci kręgosłupowe'), 140, TO_DATE('14-SEP-2015', 'DD-MON-YYYY'), NULL, 2500, 'KIERUJĄCY');


ZAD.5
